#!/bin/bash

WARN=1200
CRITICAL=2000

connections=$(lsof -p $(cat /var/run/postgresql/pgbouncer.pid) |grep 6432 |wc -l)

if [ $connections -eq 0 ]; then
   echo "PGB_OPEN CRITICAL: NOT RUNNING | pgb_open=$connections;$WARN;$CRITICAL;0"
   exit 2
fi

if [ $connections -lt $WARN ]; then
   echo "PGB_OPEN OK: $connections open connections | pgb_open=$connections;$WARN;$CRITICAL;0"
   exit 0
fi

if [ $connections -lt $CRITICAL ]; then
   echo "PGB_OPEN WARNING: $connections open connections | pgb_open=$connections;$WARN;$CRITICAL;0"
   exit 1
fi

echo "PGB_OPEN CRITICAL: $connections open connections | pgb_open=$connections;$WARN;$CRITICAL;0"
exit 2
