#!/bin/bash

PTH=/etc/nagios/nrpe_local.cfg
VERBOSE=0

while getopts ":v" opt; do
  case $opt in
    v)
      VERBOSE=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

grep '=' $PTH | cut -d'=' -f'2-' | while read cmd; do
    if [ $VERBOSE == '1' ]; then
	eval $cmd
    else
	eval $cmd > /dev/null;
	echo $?
    fi
done
